name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on DigitalOcean droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            cd /var/www/gokhangulsen.dev
            git pull origin main
            docker compose down
            docker compose up -d --build
